version: '3.7'
networks:
    CP_ASSIGNMENT:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: cp_nginx
        volumes:
            - ./docker/images/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        ports:
            - "8080:80"
        depends_on:
            - php
        networks:
            - CP_ASSIGNMENT
    php:
        build:
            context: ./docker/images/php/
            dockerfile: Dockerfile
            args:
                COMPOSER: 1
                XDEBUG: 1
        container_name: cp_php

        working_dir: /var/www
        environment:
            PHP_IDE_CONFIG: serverName=cp-code-challenge-Giuseppe
            PHP_EXTENSION_XDEBUG: "true"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        networks:
            - CP_ASSIGNMENT
    db:
        image: mariadb:10
        container_name: cp_db
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - volume_db:/var/lib/mysql:cached
        ports:
            - "3311:3306"
        networks:
            - CP_ASSIGNMENT
    rabbitmq:
        image: rabbitmq:3-management
        container_name: cp_rabbitmq
        ports:
            - "15672:15672"
        volumes:
            - volume_rabbitmq:/var/lib/rabbitmq:cached
        networks:
            - CP_ASSIGNMENT
volumes:
    volume_db:
    volume_rabbitmq:
    logs:
        driver: local