version: '3.7'
networks:
    CP_ASSIGNMENT:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: cp_nginx
        volumes:
            - ./docker/images/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        ports:
            - "8080:80"
        depends_on:
            - php
        networks:
            - CP_ASSIGNMENT
    php:
        build:
            context: ./docker/images/php/
            dockerfile: Dockerfile
            args:
                COMPOSER: 1
                XDEBUG: 1
        container_name: cp_php
        working_dir: /var/www
        environment:
            PHP_IDE_CONFIG: serverName=cp-code-challenge-Giuseppe
            PHP_EXTENSION_XDEBUG: "true"
            DB_NAME: db_name
            DB_USER: db_user
            DB_PASSWORD: db_password
            DB_HOST: db
            DB_PORT: 3306
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        networks:
            - CP_ASSIGNMENT
    db:
        build:
           context: ./docker/images/db/
           dockerfile: Dockerfile
        container_name: cp_db
        environment:
            - MYSQL_ROOT_PASSWORD=toor
            - MYSQL_DATABASE=db_name
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
        depends_on:
            - nginx
        volumes:
#            - ./docker/images/db/init:/docker-entrypoint-initdb.d
            - volume_db:/var/lib/mysql:cached
        expose:
            - "3306"
        restart: always
        networks:
            - CP_ASSIGNMENT
    rabbitmq:
        image: rabbitmq:3-management
        container_name: cp_rabbitmq
        ports:
            - "15672:15672"
        volumes:
            - volume_rabbitmq:/var/lib/rabbitmq:cached
        networks:
            - CP_ASSIGNMENT

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: cp_pma
        ports:
            - 8181:80
        environment:
            MYSQL_USERNAME: db_name
            MYSQL_ROOT_PASSWORD: toor
            PMA_HOST: "db"
            PMA_PORT: 3306
        depends_on:
            - db
        networks:
            - CP_ASSIGNMENT
volumes:
    volume_db:
    volume_rabbitmq:
    logs:
        driver: local